version: "2.2"

services:
  jobmanager:
    image: flink:1.17.1-scala_2.12-java8
    container_name: jobmanager
    ports:
      - "8383:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    image: flink:1.17.1-scala_2.12-java8
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 2
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        taskmanager.memory.network.fraction: 0.1
        taskmanager.memory.network.min: 64mb
        taskmanager.memory.network.max: 1gb

  sql-client:
    image: flink:1.17.1-scala_2.12-java8
    container_name: sql-client
    command: bin/sql-client.sh
    depends_on:
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager