# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  mongodb:
    image: docker.io/bitnami/mongodb:6.0
    hostname: mongodb-server
    container_name: mongodb-server
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    restart: always

volumes:
  mongodb_data:
    driver: local

networks:
  default:
    name: my_docker_network
    external: true