version: '3.7'

services:
  postgresdb:
    image: 'bitnami/postgresql:latest'
    container_name: postgresdb
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
      - ./sql:/data/sql
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=my_database
    restart: always

  postgresql-slave:
    image: 'bitnami/postgresql:latest'
    container_name: postgresql-slave
    ports:
      - '5433:5432'
    depends_on:
      - postgresdb
    volumes:
      - 'postgresql_slave_data:/bitnami/postgresql'
      - ./sql:/data/sql
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresdb
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_PASSWORD=postgres
    restart: always
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 1212:80
    environment:
      PGADMIN_DEFAULT_EMAIL: dmitri.mahayana@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./sql:/data/sql
      - pgadmin:/var/lib/pgadmin
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 2121:8080
    restart: always

volumes:
  postgresql_master_data:
  postgresql_slave_data:
  pgadmin:

networks:
  default:
    name: my_docker_network
    external: true